kind: pipeline
name: default

steps:
# Restore the cache if it exists
- name: restore-cache
  image: homerovalle/drone-gcs-cache
  settings:
    pull: true
    bucket: bip-drone-dependency-cache
    json_key:
      from_secret: gcs_credentials
    restore: true

- name: authenticate
  image: robertstettner/drone-mvn-auth
  pull: true
  settings:
    servers:
      from_secret: maven_servers

- name: build
  image: maven:3-jdk-8
  commands:
    - mvn compile -U -P ssb-bip -Djdk.tls.client.protocols="TLSv1.2" -Dmaven.repo.local=/drone/src/.m2/repository -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --global-settings settings.xml
  depends_on:
    - authenticate
    - restore-cache

- name: test
  image: maven:3-jdk-8
  commands:
    # Create a service account keyfile to be used by GCS tests
    - mkdir secret
    - printf "%s" "$GAC" > secret/gcs_sa_test.json
    - mvn verify test -P ssb-bip,coverage -Dmaven.repo.local=/drone/src/.m2/repository --batch-mode --global-settings settings.xml
  environment:
    DAPLA_SPARK_SERVICE_ACCOUNT_KEY_FILE: secret/gcs_sa_test.json
    DAPLA_SPARK_TEST_BUCKET: bip-drone-dependency-cache
    GAC:
      from_secret: gcs_credentials
  depends_on:
    - build

- name: codecov
  image: alpine:3
  commands:
    - apk add --no-cache bash curl findutils git
    - curl -s https://codecov.io/bash | bash
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  depends_on:
    - test

- name: codacy
  image: maven:3-jdk-8
  commands:
    - curl -Ls -o codacy-coverage-reporter "https://github.com/codacy/codacy-coverage-reporter/releases/download/6.1.3/codacy-coverage-reporter-linux-6.1.3"
    - chmod +x codacy-coverage-reporter
    - ./codacy-coverage-reporter report -l Java -r target/site/jacoco/jacoco.xml
  environment:
    CODACY_PROJECT_TOKEN:
      from_secret: codacy_token
  depends_on:
    - test

- name: sonarqube
  image: maven:3-jdk-8
  commands:
    - mvn -Djdk.tls.client.protocols="TLSv1.2" -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_PROJECTKEY sonar:sonar -P ssb-bip,coverage -Dmaven.repo.local=/drone/src/.m2/repository -Dmaven.javadoc.skip=true --batch-mode --global-settings settings.xml
  environment:
    SONAR_HOST_URL: https://sonarqube.prod-bip-ci.ssb.no
    SONAR_PROJECTKEY:
      from_secret: sonar_token
  depends_on:
    - codacy
    - codecov

- name: publish-maven
  image: maven:3-jdk-8
  commands:
    - mvn clean package deploy -P ssb-bip -Dmaven.repo.local=/drone/src/.m2/repository -DskipTests=true -Djdk.tls.client.protocols="TLSv1.2" --batch-mode --global-settings settings.xml
  when:
    ref:
      - refs/heads/develop
      - refs/tags/*
  depends_on:
    - sonarqube

- name: publish-docker-zeppelin
  image: plugins/gcr
  settings:
    dockerfile: docker/zeppelin/Dockerfile
    repo: eu.gcr.io/prod-bip/ssb/lds-zeppelin
    registry: eu.gcr.io
    auto_tag: true
    json_key:
      from_secret: gcr_credentials
  when:
    ref:
      - refs/heads/develop
      - refs/tags/*
  depends_on:
    - publish-maven

- name: publish-docker-polynote
  image: plugins/gcr
  settings:
    dockerfile: docker/polynote/Dockerfile
    repo: eu.gcr.io/prod-bip/ssb/lds-polynote
    registry: eu.gcr.io
    auto_tag: true
    json_key:
      from_secret: gcr_credentials
  when:
    ref:
      - refs/heads/develop
      - refs/tags/*
  depends_on:
    - publish-maven

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook_url
    channel: bip-ci-test
  when:
    status: [ success, failure ]
  depends_on:
    - publish-maven
    - publish-docker-zeppelin
    - publish-docker-polynote

# Rebuild cache if it has changed with this build
- name: rebuild-cache
  image: homerovalle/drone-gcs-cache
  settings:
    pull: true
    bucket: bip-drone-dependency-cache
    json_key:
      from_secret: gcs_credentials
    rebuild: true
    mount:
      - .m2/repository
  depends_on:
    - publish-maven

# OPTIONAL: Flush the cache of old cache items (older than 14 days)
- name: flush-cache
  image: homerovalle/drone-gcs-cache
  settings:
    pull: true
    bucket: bip-drone-dependency-cache
    json_key:
      from_secret: gcs_credentials
    flush: true
    flush_age: 14
  depends_on:
    - publish-maven

---
kind: secret
name: maven_servers
get:
  path: drone-maven-servers
  name: ssb-bip-maven-servers

---
kind: secret
name: slack_webhook_url
get:
  path: drone-slack-webhook-url
  name: slack-webhook-url
---
kind: secret
name: sonar_host
get:
  path: drone-sonarqube-configuration
  name: url
---
kind: secret
name: sonar_token
get:
  path: drone-sonarqube-configuration
  name: token
---
kind: secret
name: gcr_credentials
get:
  path: drone-gcr-credentials
  name: gcr-credentials
---
kind: secret
name: gcs_credentials
get:
  path: drone-gcs-credentials
  name: gcs-credentials
