kind: pipeline
name: default

steps:
# Restore the cache if it exists
- name: restore-cache
  image: homerovalle/drone-gcs-cache
  settings:
    pull: true
    bucket: bip-drone-dependency-cache
    json_key:
      from_secret: gcs_credentials
    restore: true

- name: authenticate
  image: robertstettner/drone-mvn-auth
  pull: true
  settings:
    servers:
      from_secret: maven_servers

- name: publish-maven
  image: maven:3-jdk-8
  commands:
    - mvn clean deploy -P ssb-bip -Dmaven.repo.local=/drone/src/.m2/repository -DskipTests=true -Djdk.tls.client.protocols="TLSv1.2" --batch-mode --global-settings settings.xml
  depends_on:
    - authenticate
    - restore-cache

- name: docker-dapla-zeppelin
  image: plugins/gcr
  settings:
    dockerfile: docker/zeppelin/Dockerfile
    repo: eu.gcr.io/prod-bip/dapla-zeppelin
    registry: eu.gcr.io
    tags:
      - latest
      - ${DRONE_BRANCH//\//-}-${DRONE_COMMIT_SHA:0:8}
    json_key:
      from_secret: gcr_credentials
  when:
    event: push
  depends_on:
    - publish-maven

- name: docker-dapla-polynote
  image: plugins/gcr
  settings:
    dockerfile: docker/polynote/Dockerfile
    repo: eu.gcr.io/prod-bip/dapla-polynote
    registry: eu.gcr.io
    tags:
      - latest
      - ${DRONE_BRANCH//\//-}-${DRONE_COMMIT_SHA:0:8}
    json_key:
      from_secret: gcr_credentials
  when:
    event: push
  depends_on:
    - publish-maven

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook_url
    channel: bip-ci-test
  when:
    status: [ success, failure ]
  depends_on:
    - publish-maven
    - docker-dapla-zeppelin
    - docker-dapla-polynote

# Rebuild cache if it has changed with this build
- name: rebuild-cache
  image: homerovalle/drone-gcs-cache
  settings:
    pull: true
    bucket: bip-drone-dependency-cache
    json_key:
      from_secret: gcs_credentials
    rebuild: true
    mount:
      - .m2/repository
  depends_on:
    - publish-maven

# OPTIONAL: Flush the cache of old cache items (older than 14 days)
- name: flush-cache
  image: homerovalle/drone-gcs-cache
  settings:
    pull: true
    bucket: bip-drone-dependency-cache
    json_key:
      from_secret: gcs_credentials
    flush: true
    flush_age: 14
  depends_on:
    - publish-maven

---
kind: secret
name: maven_servers
get:
  path: drone-maven-servers
  name: ssb-bip-maven-servers

---
kind: secret
name: slack_webhook_url
get:
  path: drone-slack-webhook-url
  name: slack-webhook-url
---
kind: secret
name: sonar_host
get:
  path: drone-sonarqube-configuration
  name: url
---
kind: secret
name: sonar_token
get:
  path: drone-sonarqube-configuration
  name: token
---
kind: secret
name: gcr_credentials
get:
  path: drone-gcr-credentials
  name: gcr-credentials
---
kind: secret
name: gcs_credentials
get:
  path: drone-gcs-credentials
  name: gcs-credentials
