package no.ssb.dapla.gcs.token.broker;

import java.io.IOException;
import java.util.Calendar;

import com.google.api.client.auth.oauth2.Credential;
import com.google.cloud.hadoop.util.CredentialFactory;
import no.ssb.dapla.gcs.token.delegation.BrokerTokenIdentifier;
import no.ssb.dapla.gcs.token.issuer.SignedJWTProvider;
import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.security.UserGroupInformation;

import com.google.cloud.hadoop.util.AccessTokenProvider;

// Classes dynamically generated by protobuf-maven-plugin:
//import com.google.cloud.broker.apps.brokerserver.protobuf.GetAccessTokenRequest;
//import com.google.cloud.broker.apps.brokerserver.protobuf.GetAccessTokenResponse;


public final class BrokerAccessTokenProvider implements AccessTokenProvider {

    private Configuration config;
    private AccessToken accessToken;
    private BrokerTokenIdentifier tokenIdentifier;
    private Text service;
    private CredentialFactory credentialFactory = new CredentialFactory();

    private final static AccessToken EXPIRED_TOKEN = new AccessToken("", -1L);

    public BrokerAccessTokenProvider(Text service) {
        this.service = service;
        this.accessToken = EXPIRED_TOKEN;
    }

    public BrokerAccessTokenProvider(Text service, BrokerTokenIdentifier bti) {
        this.service = service;
        this.tokenIdentifier = bti;
        this.accessToken = EXPIRED_TOKEN;
    }

    @Override
    public AccessToken getAccessToken() {
        return this.accessToken;
    }

    @Override
    public void refresh() {
        UserGroupInformation currentUser;
        UserGroupInformation loginUser;
        try {
            currentUser = UserGroupInformation.getCurrentUser();
            loginUser = UserGroupInformation.getLoginUser();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        String sessionToken;

        if (tokenIdentifier != null) {
            sessionToken = tokenIdentifier.getSessionToken();
        }
        else {
            sessionToken = null;
        }
        /*
        GetAccessTokenResponse response = loginUser.doAs((PrivilegedAction<GetAccessTokenResponse>) () -> {
            BrokerGateway gateway = new BrokerGateway(config, sessionToken);
            GetAccessTokenRequest request = GetAccessTokenRequest.newBuilder()
                    .setScope(BrokerTokenIdentifier.BROKER_SCOPE)
                    .setOwner(currentUser.getUserName())
                    .setTarget(service.toString())
                    .build();
            GetAccessTokenResponse r = gateway.getStub().getAccessToken(request);
            gateway.getManagedChannel().shutdown();
            return r;
        });

        String tokenString = response.getAccessToken();
        long expiresAt = response.getExpiresAt();
        accessToken = new AccessToken(tokenString, expiresAt);
         */
        Calendar expires = Calendar.getInstance();
        expires.add(Calendar.MINUTE, 5);
        System.out.println("Issuing access token");
        try {
            //SignedJWTProvider jwtProvider = new SignedJWTProvider(true);
            //accessToken = jwtProvider.getAccessToken(currentUser.getUserName(), BrokerTokenIdentifier.BROKER_SCOPE);
        } catch (Exception e) {
            System.out.println("SignedJWTProvider failed");
            e.printStackTrace();
        }
        try {
            // If parameter spark.hadoop.google.cloud.auth.service.account.json.keyfile is set
            // credentialFactory.getCredentialFromJsonKeyFile(...)
            Credential credential = credentialFactory.getCredentialFromMetadataServiceAccount();
            accessToken =  new AccessToken(credential.getAccessToken(), credential.getExpirationTimeMilliseconds());
            System.out.println("Issuing access token");
        } catch (Exception e) {
            System.out.println("credentialFactory failed");
            throw new RuntimeException(e);
        }
    }

    @Override
    public void setConf(Configuration config) {
        this.config = config;
    }

    @Override
    public Configuration getConf() {
        return this.config;
    }

}